# Generated by Django 3.2.5 on 2022-06-07 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bid_value', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('list_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('bids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.bid')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.comment')),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
