# Generated by Django 3.2.5 on 2022-06-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220607_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
