# Generated by Django 3.2.5 on 2022-06-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20220608_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_id',
            new_name='bidId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_created',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='list_id',
            new_name='listId',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentId',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='bids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listin', to='auctions.bid'),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
