# Generated by Django 3.2.5 on 2022-06-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20220608_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listId',
            new_name='list_id',
        ),
    ]
