# Generated by Django 3.2.5 on 2022-06-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_commentid_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
