# Generated by Django 3.2.5 on 2022-06-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220609_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
