# Generated by Django 3.2.5 on 2022-06-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bid_bidid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creation_time',
            new_name='time_created',
        ),
    ]
