# Generated by Django 3.2.5 on 2022-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_lister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(related_name='comment_item', to='auctions.Comment'),
        ),
    ]
